//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class marketbook
    {
        public string MarketId { get; set; }
        public int RefreshNr { get; set; }
        public Nullable<System.DateTime> RefreshTS { get; set; }
        public string IsMarketDataDelayed { get; set; }
        public string Status { get; set; }
        public Nullable<int> BetDelay { get; set; }
        public string IsInplay { get; set; }
        public Nullable<int> NumberOfWinners { get; set; }
        public Nullable<int> NumberOfRunners { get; set; }
        public Nullable<int> NumberOfActiveRunners { get; set; }
        public Nullable<double> TotalMatched { get; set; }
        public Nullable<double> TotalAvailable { get; set; }
        public Nullable<double> OVRBack { get; set; }
        public Nullable<double> OVRLay { get; set; }
    }
}
