//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bfmsEntities : DbContext
    {
        public bfmsEntities()
            : base("name=bfmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<marketbook> marketbooks { get; set; }
        public virtual DbSet<marketcatalogue> marketcatalogues { get; set; }
        public virtual DbSet<marketdescription> marketdescriptions { get; set; }
        public virtual DbSet<runner> runners { get; set; }
        public virtual DbSet<runnerdescription> runnerdescriptions { get; set; }
        public virtual DbSet<volume> volumes { get; set; }
    }
}
