//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class runnerdescription
    {
        public string MarketId { get; set; }
        public int SelectionId { get; set; }
        public string RunnerName { get; set; }
        public Nullable<double> Handicap { get; set; }
    }
}
