//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class runner
    {
        public string MarketId { get; set; }
        public int SelectionId { get; set; }
        public int RefreshNr { get; set; }
        public string Name { get; set; }
        public string RunnerStatus { get; set; }
        public Nullable<System.DateTime> RemovalDate { get; set; }
        public Nullable<double> Handicap { get; set; }
        public Nullable<double> AdjustmentFactor { get; set; }
        public Nullable<double> ToBackTotal { get; set; }
        public Nullable<double> ToLayTotal { get; set; }
        public Nullable<double> BackLayRatio { get; set; }
        public Nullable<double> LastPriceTraded { get; set; }
        public Nullable<double> VolPrice { get; set; }
        public Nullable<double> AvgPrice { get; set; }
        public Nullable<double> Matched { get; set; }
        public Nullable<double> MatchedTotal { get; set; }
        public Nullable<double> VolumeBack { get; set; }
        public Nullable<double> VolumeLay { get; set; }
        public Nullable<double> InsMoneyBack { get; set; }
        public Nullable<double> InsMoneyLay { get; set; }
        public Nullable<double> Indikator1 { get; set; }
        public Nullable<double> Indikator2 { get; set; }
    }
}
