//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class volume
    {
        public string MarketId { get; set; }
        public int SelectionId { get; set; }
        public int RefreshNr { get; set; }
        public long LaufNr { get; set; }
        public string Type { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Size { get; set; }
    }
}
